name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy node app for ovh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd ~/att-manager
            git pull origin master
            git submodule update --init
            npm install --production
            npm run webpack:prod
            pm2 restart att-manager
